{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
    name: virocon
    version: {{ data.get('version') }}

source:
    path: ..
    
build:
    noarch: python
    number: 0
    
requirements:
  host:
    - python >=3.7
    - pip
    - matplotlib>=2.2.0
    - networkx
    - numpy
    - pandas
    - scikit-learn
    - scipy
  run:
    - python >=3.7
    - matplotlib>=2.2.0
    - networkx
    - numpy
    - pandas
    - scikit-learn
    - scipy
    
test:
  imports:
    - virocon
  commands:
    - pip check
  requires:
    - pip
    
about:
    home: https://github.com/virocon-organization/virocon
    license: MIT license
    license_file: 
        - LICENSE
    summary: compute environmental contours

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
