name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check . # Run linting, fails on issues.
      - name: Check formatting
        run: |
          ruff format --check . || (
            echo "Formatting issues detected. Showing diff:" &&
            ruff format . &&
            git diff
          )
